name: "7.4"
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'src/7.4/**'
      - '.github/workflows/php-7.4.yml'
  schedule:
    - cron:  '30 1 1,15 * *'

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [7.4]
        patchVersion: [23,24,25,26,27]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build php image
        run: docker build --target php -t openmage/php:${{ matrix.version }}.${{ matrix.patchVersion }} -f src/${{ matrix.version }}/src/Dockerfile --build-arg PHP_VERSION=${{ matrix.version }}.${{ matrix.patchVersion }} src/${{ matrix.version }}/src/

      - name: Build toolbox image
        run: docker build --target toolbox -t openmage/php:${{ matrix.version }}.${{ matrix.patchVersion }}-toolbox -f src/${{ matrix.version }}/src/Dockerfile --build-arg PHP_VERSION=${{ matrix.version }}.${{ matrix.patchVersion }} src/${{ matrix.version }}/src/

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: publish php image to dockerhub
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: docker push openmage/php:${{ matrix.version }}.${{ matrix.patchVersion }}

      - name: publish toolbox image to dockerhub
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: docker push openmage/php:${{ matrix.version }}.${{ matrix.patchVersion }}-toolbox
