name: "8.0"
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'src/8.0/**'
      - '.github/workflows/php-8.0.yml'
  schedule:
    - cron:  '30 1 1,15 * *'

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ['8.0']
        patchVersion: [0,1,2,3,5]
    steps:
      - uses: actions/checkout@v1

      - name: Build php image
        run: docker build --target php -t openmage/php:${{ matrix.version }}.${{ matrix.patchVersion }} -f src/${{ matrix.version }}/src/Dockerfile --build-arg PHP_VERSION=${{ matrix.version }}.${{ matrix.patchVersion }} src/${{ matrix.version }}/src/

      - name: Build toolbox image
        run: docker build --target toolbox -t openmage/php:${{ matrix.version }}.${{ matrix.patchVersion }}-toolbox -f src/${{ matrix.version }}/src/Dockerfile --build-arg PHP_VERSION=${{ matrix.version }}.${{ matrix.patchVersion }} src/${{ matrix.version }}/src/

      - uses: azure/docker-login@v1
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: publish php image to dockerhub
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: docker push openmage/php:${{ matrix.version }}.${{ matrix.patchVersion }}
      - name: publish toolbox image to dockerhub
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: docker push openmage/php:${{ matrix.version }}.${{ matrix.patchVersion }}-toolbox
