name: "8.1"
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'src/8.1/**'
      - '.github/workflows/php-8.1.yml'
  schedule:
    - cron:  '30 1 1,15 * *'

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ['8.1']
        patchVersion: [5,6,7,8,9]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build php image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: openmage/php:${{ matrix.version }}.${{ matrix.patchVersion }}
          context: ./src/${{ matrix.version }}/src
          file: ./src/${{ matrix.version }}/src/Dockerfile
          target: php
          build-args: |
            PHP_VERSION=${{ matrix.version }}.${{ matrix.patchVersion }}
      - name: Build toolbox image
        uses: docker/build-push-action@v2
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: openmage/php:${{ matrix.version }}.${{ matrix.patchVersion }}-toolbox
          context: ./src/${{ matrix.version }}/src
          file: ./src/${{ matrix.version }}/src/Dockerfile
          target: toolbox
          build-args: |
            PHP_VERSION=${{ matrix.version }}.${{ matrix.patchVersion }}
