name: "Pull Request"
on:
  pull_request:
    branches:
    - main

jobs:
  lint:
    strategy:
      matrix:
        version: ['7.4', '8.0', '8.1']
    runs-on: ubuntu-latest
    container: pipelinecomponents/hadolint:latest
    steps:
      - uses: actions/checkout@v2
      - uses: hadolint/hadolint-action@v1.5.0
        with:
          dockerfile: ./src/${{ matrix.version }}/src/Dockerfile
