name: "Pull Request"
on:
  pull_request:
    branches:
    - main

jobs:
  lint:
    strategy:
      matrix:
        version: ['8.1', '8.2', '8.3', '8.4']
    runs-on: ubuntu-latest
    container: pipelinecomponents/hadolint:latest
    steps:
      - uses: actions/checkout@v4
      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: ./src/${{ matrix.version }}/src/Dockerfile
