name: "Pull Request"
on:
  pull_request:
    branches:
    - master

jobs:
  lint:
    strategy:
      matrix:
        version: ['7.2', '7.3', '7.4', '8.0' ]
    runs-on: ubuntu-latest
    container: pipelinecomponents/hadolint:latest
    steps:
    - uses: actions/checkout@v1
    - name: Run hadolint
      run: hadolint src/${{ matrix.version }}/src/Dockerfile
